# _config.yml
title: Josiel Jefferson - Downloads
description: Arquivos para download
baseurl: "" # Se o site estiver na raiz do domínio (ex: user.github.io)
url: "https://josieljluz.github.io/josieljluz.github.io.oficial"
